import { Outfit } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";
import { Toaster } from "sonner";
import MotionWrapperDelay from "./_components/FramerMotion/MotionWrapperDelay";

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: "Short Video AI Generator",
  description: "Generated by create CodeNow101",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <div className="animated-bg fixed -z-10 inset-0 opacity-90" />
        <ClerkProvider
          dynamic
          appearance={{
            baseTheme: shadesOfPurple,
            variables: {
              colorPrimary: "#3b82f6",
              colorBackground: "#000",
              colorInputBackground: "#2D3748",
              colorInputText: "#F3F4F6",
            },
            elements: {
              formButtonPrimary: "bg-indigo-800 hover:bg-indigo-900 text-white",
              card: "gradient-background2",
              headerTitle: "text-indigo-800",
              headerSubtitle: "text-purple-700",
            },
          }}
        >
          <Provider>
            {children}
          </Provider>
        </ClerkProvider>

        <Toaster richColors />

        <MotionWrapperDelay
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.9, delay: 0.8 }}
          variants={{
            hidden: { opacity: 0, x: 20 },
            visible: { opacity: 1, x: 0 },
          }}
        >
          <footer className="gradient-background2 py-12 bg-opacity-20">
            <div className="mx-auto px-4 text-center text-gray-300">
              <p>
                © {new Date().getFullYear()} CodeNow101. All Rights Reserved
              </p>
            </div>
          </footer>
        </MotionWrapperDelay>
      </body>
    </html>
  );
}